---
- name: Create user
  ansible.builtin.user:
    name: "{{ chain_hyperliquid_user }}"
    group: users
    system: true
    create_home: true
    state: present

- name: Add user to systemd-journal group
  ansible.builtin.user:
    name: "{{ chain_hyperliquid_user }}"
    groups: systemd-journal
    append: true

- name: Disable IPv6
  ansible.posix.sysctl:
    name: "{{ item }}"
    value: "1"
    state: present
    reload: true
  with_items:
    - net.ipv6.conf.all.disable_ipv6
    - net.ipv6.conf.default.disable_ipv6
    - net.ipv6.conf.lo.disable_ipv6

# https://github.com/b-harvest/awesome-hyperliquid-validators/blob/main/OS_Kernel_Parameter.md
- name: Tuning OS kernel
  ansible.posix.sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: present
    reload: true
  with_items:
    - { name: net.core.rmem_max, value: 268435456 }
    - { name: net.core.wmem_max, value: 268435456 }
    - { name: net.ipv4.conf.all.arp_announce, value: 2 }
    - { name: net.ipv4.conf.all.arp_filter, value: 1 }
    - { name: net.ipv4.conf.all.arp_ignore, value: 1 }
    - { name: net.ipv4.conf.default.arp_filter, value: 1 }
    - { name: net.ipv4.tcp_no_metrics_save, value: 1 }
    - { name: net.ipv4.tcp_rmem, value: 4096 87380 134217728 }
    - { name: net.ipv4.tcp_wmem, value: 4096 65536 134217728 }
    - { name: net.core.default_qdisc, value: fq }
    - { name: net.ipv4.tcp_congestion_control, value: bbr }

- name: Hl-visor
  ansible.builtin.include_tasks: hl-visor.yml

- name: Hypermon
  ansible.builtin.include_tasks: hypermon.yml

- name: Validator-observability
  ansible.builtin.include_role:
    name: binarybuilders.validators.observability
  vars:
    observability_alerts: "{{ chain_hyperliquid_alerts }}"
    observability_chain_id: hyperliquid-{{ chain_hyperliquid_network }}

- name: Deploy justfile
  ansible.builtin.template:
    src: justfile.j2
    dest: /home/{{ chain_hyperliquid_user }}/justfile
    owner: "{{ chain_hyperliquid_user }}"
    group: users
    mode: "0644"

- name: Configure shell
  ansible.builtin.include_role:
    name: binarybuilders.servers.configure_hosts
    tasks_from: shell.yml
  vars:
    configure_hosts_users_username: "{{ chain_hyperliquid_user }}"
