---
- name: Quadlet volume file
  containers.podman.podman_volume:
    name: victorialogs
    state: quadlet
    label:
      app: victorialogs
  notify: Restart victorialogs

- name: Quadlet container file
  containers.podman.podman_container:
    name: victorialogs
    image: "{{ victoriametrics_victorialogs_image }}"
    state: quadlet
    network: host
    volumes:
      - victorialogs.volume:/victoria-logs-data:bind
    label:
      app: victorialogs
    quadlet_options:
      - |

        [Unit]
        Description=victorialogs
        After=network-online.target
        Wants=network-online.target

        [Service]
        Restart=always
        RestartSec=3
        TimeoutStartSec=900

        [Install]
        WantedBy=default.target
  notify: Restart victorialogs

- name: Enable systemd service
  ansible.builtin.systemd:
    name: victorialogs
    enabled: true
    state: started
    daemon_reload: true

- name: Alloy | Edit configuration
  ansible.builtin.blockinfile:
    path: "{{ victoriametrics_alloy_config_path }}/config.alloy"
    marker: /// {mark} ANSIBLE MANAGED BLOCK - victorialogs
    append_newline: true
    block: |
      prometheus.scrape "victorialogs" {
        clustering {
          enabled = true
        }
        targets = [{
          __address__ = "{{ ansible_hostname }}:9428",
        }]
        forward_to      = [prometheus.remote_write.victoriametrics.receiver]
      }

  notify: Restart alloy
