---
- name: Restart Semaphoreui
  ansible.builtin.systemd_service:
    name: "{{ item }}"
    daemon_reload: true
    enabled: true
    state: restarted
  loop:
    - semaphoreui
    - semaphoreui-db
