---
- name: Restart bridge-celestia-app-{{ chain_celestia_network }}
  ansible.builtin.systemd_service:
    name: bridge-celestia-app-{{ chain_celestia_network }}
    state: restarted

- name: Restart bridge-celestia-node-{{ chain_celestia_network }}
  ansible.builtin.systemd_service:
    name: bridge-celestia-node-{{ chain_celestia_network }}
    state: restarted

- name: Restart validator-celestia-app-{{ chain_celestia_network }}
  ansible.builtin.systemd_service:
    name: validator-celestia-app-{{ chain_celestia_network }}
    state: restarted

- name: Restart celestia-da-otel-collector-{{ chain_celestia_network }}
  ansible.builtin.systemd_service:
    name: celestia-da-otel-collector-{{ chain_celestia_network }}
    state: restarted

- name: Restart cosmos-validator-watcher-{{ chain_celestia_network }}
  ansible.builtin.systemd_service:
    name: cosmos-validator-watcher-{{ chain_celestia_network }}
    state: restarted

- name: Restart alloy
  ansible.builtin.systemd_service:
    name: alloy
    daemon_reload: true
    state: restarted

- name: Restart vmalert
  ansible.builtin.systemd_service:
    name: vmalert
    daemon_reload: true
    state: restarted
  delegate_to: observability
