---
- name: Restart Podman-exporter
  ansible.builtin.systemd_service:
    name: podman-exporter
    daemon_reload: true
    enabled: true
    state: restarted

- name: Restart alloy
  ansible.builtin.systemd_service:
    name: alloy
    daemon_reload: true
    state: restarted
