---
- name: Restart Node-exporter
  ansible.builtin.systemd_service:
    name: node-exporter
    daemon_reload: true
    state: restarted

- name: Restart alloy
  ansible.builtin.systemd_service:
    name: alloy
    daemon_reload: true
    state: restarted
