---
- name: Alloy | Edit configuration
  ansible.builtin.blockinfile:
    path: "{{ observability_alloy_config_path }}/config.alloy"
    marker: /// {mark} ANSIBLE MANAGED BLOCK - {{ observability_chain_id }}
    append_newline: true
    block: |
      prometheus.scrape "cosmos_sdk_{{ observability_chain_id | replace('-', '_') }}" {
        clustering {
          enabled = true
        }
        targets = [{
          __address__ = "{{ ansible_hostname }}:{{ observability_prometheus_sdk_prometheus_port }}",
        }]
        forward_to      = [prometheus.remote_write.victoriametrics.receiver]
      }

      prometheus.scrape "cosmos_validator_watcher_{{ observability_chain_id | replace('-', '_') }}" {
        clustering {
          enabled = true
        }
        targets = [{
          __address__ = "{{ ansible_hostname }}:{{ observability_prometheus_watcher_prometheus_port }}",
        }]
        forward_to      = [prometheus.remote_write.victoriametrics.receiver]
      }

  notify: Restart alloy

- name: VMAlert | Deploy generic cosmos validator alerts
  when: observability_alerts is defined and observability_alerts | bool
  ansible.builtin.template:
    src: cosmos-validator-generic.yml.j2
    dest: "{{ observability_vmalert_config_path }}/cosmos-validator-generic.yml"
    mode: "0644"
  delegate_to: observability
  notify: Restart vmalert

- name: VMAlert | Deploy cosmos validator alerts by chain
  when: observability_alerts is defined and observability_alerts | bool
  ansible.builtin.template:
    src: cosmos-validator-by-chain.yml.j2
    dest: "{{ observability_vmalert_config_path }}/cosmos-validator-{{ observability_chain_id }}.yml"
    mode: "0644"
  delegate_to: observability
  notify: Restart vmalert
