---
- name: VMAlert | Deploy global alerts
  when: observability_alerts is defined and observability_alerts | bool
  ansible.builtin.template:
    src: global.yml.j2
    dest: "{{ observability_vmalert_config_path }}/global.yml"
    mode: "0644"
  delegate_to: observability
  notify: Restart vmalert

- name: Cosmos
  when: observability_prometheus_sdk_prometheus_port is defined or observability_prometheus_watcher_prometheus_port is defined
  ansible.builtin.include_tasks: cosmos.yml
