---
chain_celestia_alloy_config_path: /root/.local/share/alloy
chain_celestia_config_path: /root/.local/share/celestia-da-otel-collector
chain_celestia_vmalert_config_path: /root/.local/share/vmalert
